#Image Annotations
#Mon May 04 09:26:46 MYT 2026
C\:\\Users\\User\\Downloads\\TSHIRT\ COMP\\2.png=TEST
C\:\\Users\\User\\Downloads\\Wedding\ Board\\2.png=test
C\:\\Users\\User\\Downloads\\Wedding\ Board\\3.png=hello
C\:\\Users\\User\\Downloads\\Wedding\ Board\\5.png=hello
C\:\\Users\\User\\Downloads\\design\ tshirt\\3.png=try
