#Image Annotations
#Sat May 02 23:34:53 MYT 2026
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\\photo_6319017823505682754_y.jpg=hi jake
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\\photo_6319017823505682755_y.jpg=pistahcio
