#Image Annotations
#Tue May 19 08:08:32 MYT 2026
C\:\\Users\\User\\Downloads\\Wedding\ Board\\5.png=ui
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\ VER\ 4\\banana-and-apple-color-design-free-vector.jpg=bnjbj
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\ 30\\apple-and-banana-color-icon-vector.jpg=buah pisang and apple
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\\photo_6319017823505682754_y.jpg=hi jake
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\ 30\\IMG_5929.JPG=Saya sukaaa
C\:\\Users\\User\\Downloads\\Wedding\ Board\\3.png=day 1
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\ VER\ 4\\apple-and-banana-color-icon-vector.jpg=nk
C\:\\Users\\User\\Downloads\\Wedding\ Board\\1.png=
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\ VER\ 4\\IMG_5927.JPG=hbh
C\:\\Users\\User\\Downloads\\Wedding\ Board\\4.png=hello
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\ 30\\IMG_5927.JPG=Jungwon Jay Heeseung
C\:\\Users\\User\\Downloads\\ilovepdf_pages-to-jpg\ (13)\\Report\ 1\ on\ Jan\ 16,\ 2026_page-0001.jpg=lobe
C\:\\Users\\User\\Downloads\\Wedding\ Board\\2.png=hello
C\:\\Users\\aina\\Documents\\MULTIMEDIA\ PROGRAMMING\\MULTIMEDIA\ PROJECT\\GAMBAR\\photo_6319017823505682755_y.jpg=pistahcio
